export const CommuniquesFeatures = {
    READ: 'COMMUNIQUES_READ',
    READ_ALL: 'COMMUNIQUES_READ_ALL',
    READ_BY_ID: 'COMMUNIQUES_READ_BY_ID',
    CREATE: 'COMMUNIQUES_CREATE',
    UPDATE: 'COMMUNIQUES_UPDATE',
    DELETE: 'COMMUNIQUES_DELETE',
} as const;