export const CompanyFeatures = {
    READ: 'COMPANIES_READ',
    READ_ALL: 'COMPANIES_READ_ALL',
    READ_BY_ID: 'COMPANIES_READ_BY_ID',
    CREATE: 'COMPANIES_CREATE',
    UPDATE: 'COMPANIES_UPDATE',
    DELETE: 'COMPANIES_DELETE',
} as const;