export const DocumentsFeatures = {
    READ: 'DOCUMENTS_READ',
    READ_ALL: 'DOCUMENTS_READ_ALL',
    READ_BY_ID: 'DOCUMENTS_READ_BY_ID',
    CREATE: 'DOCUMENTS_CREATE',
    UPDATE: 'DOCUMENTS_UPDATE',
    DELETE: 'DOCUMENTS_DELETE',
} as const;