export const PermissionsFeatures = {
    READ: 'PERMISSIONS_READ',
    READ_ALL: 'PERMISSIONS_READ_ALL',
    READ_BY_ID: 'PERMISSIONS_READ_BY_ID',
    CREATE: 'PERMISSIONS_CREATE',
    UPDATE: 'PERMISSIONS_UPDATE',
    DELETE: 'PERMISSIONS_DELETE',
} as const;