export const PermissionsFeatures = {
    READ: 'PERMISSIONS_READ',
    READ_ALL_USERS_FEATURES: 'PERMISSIONS_READ_ALL_USERS_FEATURES',
    READ_FEATURES_BY_USER_ID: 'PERMISSIONS_READ_FEATURES_BY_USER_ID',
    READ_ALL_PAGES_WITH_FEATURES: 'PERMISSIONS_READ_ALL_PAGES_WITH_FEATURES',
    ASSIGN_USER: 'PERMISSIONS_ASSIGN_USER',
    REVOKE_USER_FEATURE: 'PERMISSIONS_REVOKE_USER_FEATURE',
    UPDATE: 'PERMISSIONS_UPDATE',
    DELETE: 'PERMISSIONS_DELETE',
} as const;