export const UserFeatures = {
    READ: 'USERS_READ',
    READ_ALL: 'USERS_READ_ALL',
    READ_BY_ID: 'USERS_READ_BY_ID',
    RESET_PASSWORD: 'USERS_RESET_PASSWORD',
    TOGGLE_ACTIVE_STATUS: 'USERS_TOGGLE_ACTIVE_STATUS',
    CREATE: 'USERS_CREATE',
    UPDATE: 'USERS_UPDATE',
    DELETE: 'USERS_DELETE',
} as const;