export const VisitHistoryGeneralFeatures = {
    READ: 'VISIT_HISTORY_READ',
    WRITE: 'VISIT_HISTORY_WRITE',
};

/* Old features that are no longer in use */
// export const VisitScheduleFeatures = {
//     READ: 'VISIT_SCHEDULES_READ',
//     READ_ALL: 'VISIT_SCHEDULES_READ_ALL',
//     READ_BY_ID: 'VISIT_SCHEDULES_READ_BY_ID',
//     CREATE: 'VISIT_SCHEDULES_CREATE',
//     UPDATE: 'VISIT_SCHEDULES_UPDATE',
//     DELETE: 'VISIT_SCHEDULES_DELETE',
//     CONFIRM_PRESENCE: 'VISIT_SCHEDULES_CONFIRM_PRESENCE',
//     CANCEL: 'VISIT_SCHEDULES_CANCEL',
// } as const;

// export const VisitPresentsFeatures = {
//     READ: 'VISIT_PRESENTS_READ',
//     READ_ALL: 'VISIT_PRESENTS_READ_ALL',
//     READ_BY_ID: 'VISIT_PRESENTS_READ_BY_ID',
//     CREATE: 'VISIT_PRESENTS_CREATE',
//     UPDATE: 'VISIT_PRESENTS_UPDATE',
//     DELETE: 'VISIT_PRESENTS_DELETE',
//     CONFIRM_EXIT: 'VISIT_PRESENTS_CONFIRM_EXIT',
// } as const;

// export const VisitHistoryFeatures = {
//     TOTAL: 'VISIT_HISTORY_READ',
//     READ_ALL: 'VISIT_HISTORY_READ_ALL',
//     READ_BY_ID: 'VISIT_HISTORY_READ_BY_ID',
//     CREATE: 'VISIT_HISTORY_CREATE',
//     UPDATE: 'VISIT_HISTORY_UPDATE',
//     DELETE: 'VISIT_HISTORY_DELETE',
//     EXPORT: 'VISIT_HISTORY_EXPORT',
// } as const;