export const VisitScheduleFeatures = {
    READ: 'VISIT_SCHEDULES_READ',
    READ_ALL: 'VISIT_SCHEDULES_READ_ALL',
    READ_BY_ID: 'VISIT_SCHEDULES_READ_BY_ID',
    CREATE: 'VISIT_SCHEDULES_CREATE',
    UPDATE: 'VISIT_SCHEDULES_UPDATE',
    DELETE: 'VISIT_SCHEDULES_DELETE',
    APPROVE: 'VISIT_SCHEDULES_APPROVE',
    CHECKIN: 'VISIT_SCHEDULES_CHECKIN',
    CHECKOUT: 'VISIT_SCHEDULES_CHECKOUT',
} as const;

export const VisitHistoryFeatures = {
    READ_ALL: 'VISIT_HISTORY_READ_ALL',
    READ_BY_ID: 'VISIT_HISTORY_READ_BY_ID',
    CREATE: 'VISIT_HISTORY_CREATE',
    UPDATE: 'VISIT_HISTORY_UPDATE',
    DELETE: 'VISIT_HISTORY_DELETE',
} as const;