export const VisitorFeatures = {
    READ_ALL: 'VISITORS_READ_ALL',
    READ_BY_ID: 'VISITORS_READ_BY_ID',
    READ_BY_COMPANIE: 'VISITORS_READ_BY_COMPANIE',
    CREATE: 'VISITORS_CREATE',
    UPDATE: 'VISITORS_UPDATE',
    DELETE: 'VISITORS_DELETE',
    MARK_AS_LEFT: 'VISITORS_MARK_AS_LEFT',
} as const;


